name: linting

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    phpstan:
        name: '🧹 Psalm'
        runs-on: ubuntu-latest
        steps:
            - name: '☁️ checkout repository'
              uses: actions/checkout@v7
              with:
                  persist-credentials: false

            - name: "🧹 Run Psalm"
              uses: docker://ghcr.io/psalm/psalm-github-actions
              with:
                composer_require_dev: true
                composer_ignore_platform_reqs: true
                # security_analysis: true
